language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="mc2:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="mc2" OCAML_VERSION="4.02.3"
  - PACKAGE="mc2" OCAML_VERSION="4.03.0"
  - PACKAGE="mc2" OCAML_VERSION="4.04.2"
  - PACKAGE="mc2" OCAML_VERSION="4.05.0"
  - PACKAGE="mc2" OCAML_VERSION="4.06.0"
    #- PACKAGE="mc2" OCAML_VERSION="4.07.0"
